# Uncomment the next line to define a global platform for your project


platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Install all subspecs
  pod 'OPCore', :git => 'https://github.com/MrBoog/Infrastructure.git', :tag=> '0.0.9'
  #Install specific subspec
  #pod 'OPCore', :git => 'https://github.com/MrBoog/Infrastructure.git', :tag=> '0.0.9', :subspecs => ['UI', 'Auth']
  #pod 'OPCore/UI', :git => 'https://github.com/MrBoog/Infrastructure.git', :tag=> '0.0.9'

end
